{% set name = "pyspike" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mariomulansky/PySpike/archive/{{ version }}.tar.gz
  sha256: 199d41af097e0b6e6583e22d4a9c3cedab51ceba4da2d940682ffefe8120a414
  patches:
    - 68.patch

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - cython
    - numpy
  run:
    - python
    - matplotlib-base

test:
  imports:
    - pyspike
    - pyspike.cython
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mariomulansky/PySpike
  summary: A Python library for the numerical analysis of spiketrain similarity
  license: BSD-2-Clause
  license_file: License.txt

extra:
  recipe-maintainers:
    - Tobias-Fischer
