{% set name = "pyspike" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mariomulansky/PySpike/archive/v{{ version }}.tar.gz
  sha256: 9531c3aa4bb648a517d440724341ebce4baabc582af6b80c72b35b30ef6dc3fb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - setuptools
    - python
    - cython
    - numpy
  run:
    - python
    - matplotlib-base
    - setuptools  # needs pkg_resources

test:
  imports:
    - pyspike
    - pyspike.cython
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mariomulansky/PySpike
  summary: A Python library for the numerical analysis of spiketrain similarity
  license: BSD-2-Clause
  license_file: License.txt

extra:
  recipe-maintainers:
    - Tobias-Fischer
