{% set name = "pyspike" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mariomulansky/PySpike/archive/{{ version }}.tar.gz
  sha256: 47031ba10a5726845982b62dcae970449ca50c4be9985a1ed0d2a021456bf25a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython
    - numpy
  run:
    - python
    - matplotlib-base
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyspike
    - pyspike.cython
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mariomulansky/PySpike
  summary: A Python library for the numerical analysis of spiketrain similarity
  license: BSD-2-Clause
  license_file: License.txt

extra:
  recipe-maintainers:
    - Tobias-Fischer
